export enum SessionStatus {
    PENDING_TUTOR_APPROVAL = 'PENDING_TUTOR_APPROVAL',
    SCHEDULED = 'SCHEDULED',
    CANCELLED_BY_TUTOR = 'CANCELLED_BY_TUTOR',
    CANCELLED_BY_STUDENT = 'CANCELLED_BY_STUDENT',
    NO_SHOW_STUDENT = 'NO_SHOW_STUDENT',
    COMPLETED = 'COMPLETED',
}
